name: hw1_env
dependencies:
  - pip
  - python=3.6
  - pip:
      - pandas
      - numpy
      - wandb
      - xgboost==1.4.1
      - catboost==0.25.1
      - lightgbm==3.2.1
      - textblob==0.15.3
